### ISSUE TITLE
Throw "com.aliyun.oss.ClientException: Read timed out " when copy large object

### ISSUE THREAD

**Issue by uncleGen** [aliyun/aliyun-spark-sdk#31]
com.aliyun.oss.ClientException: Read timed out 
[ErrorCode]: SocketTimeout 
[RequestId]: Unknown 
   at com.aliyun.oss.common.utils.ExceptionFactory.createNetworkException(ExceptionFactory.java:65) 
   at com.aliyun.oss.common.comm.DefaultServiceClient.sendRequestCore(DefaultServiceClient.java:62) 
   at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:126) 
   at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:72) 
   at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:92) 
   at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:133) 
   at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:111) 
   at com.aliyun.oss.internal.OSSObjectOperation.copyObject(OSSObjectOperation.java:298) 
   at com.aliy
un.oss.OSSClient.copyObject(OSSClient.java:465) 
   at com.aliyun.oss.OSSClient.copyObject(OSSClient.java:459)

**Comment by uncleGen** [comment]
use "Upload Part Copy" instead

**Comment by uncleGen** [comment]
Fixed with #32 and #33
